/** Hebcal geo=city tokens for Israel (Hebcal JSON API). */
export const HEBCAL_CITY_META = [
  { value: "IL-Jerusalem", he: "ירושלים", en: "Jerusalem", ru: "Иерусалим", fr: "Jérusalem" },
  { value: "IL-Tel_Aviv", he: "תל אביב", en: "Tel Aviv", ru: "Тель-Авив", fr: "Tel-Aviv" },
  { value: "IL-Haifa", he: "חיפה", en: "Haifa", ru: "Хайфа", fr: "Haïfa" },
  { value: "IL-Beer_Sheva", he: "באר שבע", en: "Be'er Sheva", ru: "Беэр-Шева", fr: "Beer-Sheva" },
  { value: "IL-Ashdod", he: "אשדוד", en: "Ashdod", ru: "Ашдод", fr: "Ashdod" },
  { value: "IL-Netanya", he: "נתניה", en: "Netanya", ru: "Нетания", fr: "Netanya" },
  { value: "IL-Rishon_LeTsiyon", he: "ראשון לציון", en: "Rishon LeZion", ru: "Ришон-ле-Цион", fr: "Rishon LeZion" },
  { value: "IL-Petah_Tikva", he: "פתח תקווה", en: "Petah Tikva", ru: "Петах-Тиква", fr: "Petah Tikva" },
  { value: "IL-Holon", he: "חולון", en: "Holon", ru: "Холон", fr: "Holon" },
  { value: "IL-Bnei_Brak", he: "בני ברק", en: "Bnei Brak", ru: "Бней-Брак", fr: "Bnei Brak" },
  { value: "IL-Ashkelon", he: "אשקלון", en: "Ashkelon", ru: "Ашкелон", fr: "Ashkelon" },
  { value: "IL-Rehovot", he: "רחובות", en: "Rehovot", ru: "Реховот", fr: "Rehovot" },
  { value: "IL-Herzliya", he: "הרצליה", en: "Herzliya", ru: "Герцлия", fr: "Herzliya" },
  { value: "IL-Ramat_Gan", he: "רמת גן", en: "Ramat Gan", ru: "Рамат-Ган", fr: "Ramat Gan" },
  { value: "IL-Bat_Yam", he: "בת ים", en: "Bat Yam", ru: "Бат-Ям", fr: "Bat Yam" },
  { value: "IL-Kfar_Saba", he: "כפר סבא", en: "Kfar Saba", ru: "Кфар-Сава", fr: "Kfar Saba" },
  { value: "IL-Raanana", he: "רעננה", en: "Raanana", ru: "Раанана", fr: "Raanana" },
  { value: "IL-Modiin", he: "מודיעין", en: "Modiin", ru: "Модиин", fr: "Modiin" },
  { value: "IL-Lod", he: "לוד", en: "Lod", ru: "Лод", fr: "Lod" },
  { value: "IL-Ramla", he: "רמלה", en: "Ramla", ru: "Рамла", fr: "Ramla" },
  { value: "IL-Acre", he: "עכו", en: "Acre", ru: "Акко", fr: "Acre" },
  { value: "IL-Nazareth", he: "נצרת", en: "Nazareth", ru: "Назарет", fr: "Nazareth" },
  { value: "IL-Eilat", he: "אילת", en: "Eilat", ru: "Эйлат", fr: "Eilat" },
  { value: "IL-Tiberias", he: "טבריה", en: "Tiberias", ru: "Тверия", fr: "Tibériade" },
];

export const DEFAULT_CONFIG = {
  title: "דוד מים חמים",
  language: "he",
  /** @type {""|"standard"|"switcher_touch"|"boiler_smarthome4u"} */
  device_profile: "",
  switcher_mode: false,
  boiler_entity: "",
  temperature_sensor: "",
  power_sensor: "",
  current_sensor: "",
  voltage_sensor: "",
  boost_time_entity: "",
  total_time_entity: "",
  work_time_entity: "",
  backlight_mode_entity: "",
  child_lock_entity: "",
  power_on_behavior_entity: "",
  boost_timer_values: "15,30,60,90",
  off_boost_minutes: 90,
  switcher_time_left_sensor: "",
  switcher_sensor_1: "",
  switcher_sensor_2: "",
  switcher_icon_sensor: "",
  switcher_timer_values: "15,30,45,60",
  timer_values: "15,30,60",
  card_theme: "dark_glass",
  ui_scale_percent: 100,
  mobile_popup_fullscreen: true,
  boiler_flow_image: "/local/boiler-card/boiler-flow.png",
  hide_boiler_flow_image: false,
  duration_entity: "",
  timer_entity: "",
  script_on_timed: "",
  script_on_continuous: "",
  script_off: "",
  integration_entry_id: "",
  hebcal_city: "",
  service_run_timed: "boiler_manager.run_timed",
  service_on_continuous: "boiler_manager.turn_on_continuous",
  service_off: "boiler_manager.turn_off",
  service_create_schedule: "boiler_manager.create_schedule",
  service_create_timeline: "boiler_manager.create_timeline",
  service_update_schedule: "boiler_manager.update_schedule",
  service_delete_schedule: "boiler_manager.delete_schedule",
  service_import_tasks: "boiler_manager.import_tasks",
  service_export_tasks: "boiler_manager.export_tasks",
  service_set_vacation_mode: "boiler_manager.set_vacation_mode",
  service_clear_task_history: "boiler_manager.clear_task_history",
  holiday_entity: "",
  shabbat_entity: "",
  holiday_active_states: "on,home,active,true",
  holiday_timer_policy: "allow",
  holiday_task_policy: "allow",
  holiday_regular_timer_policy: "allow",
  holiday_regular_task_policy: "allow",
  holiday_shabbat_timer_policy: "allow",
  holiday_shabbat_task_policy: "allow",
  shabbat_timer_policy: "allow",
  shabbat_task_policy: "allow",
  state_on_values: ["on"],
  state_off_values: ["off", "idle", "standby", "unavailable", "unknown"],
};
